---
name: test-function
enabled: true
entry_point: main()
triggers:
  - type: dataset
    column: block_number
    path: eth
  - type: cron
    schedule: * * * * * 7 / 0
    path: eth.blocks
output:
- type: dataset
   name: uniswap_v2_eth_usdc
- type: webhook
   name: uniswap_v2_eth_usdc_webhook
   url: http:?....
   include_data: true
